import { Badge, Card, LoadingState, ProgressBar } from "../components/common/UI";
import { useLearning } from "../contexts/LearningContext";
import { humanize, humanizeMisconception, percent } from "../utils/format";

export function Progress() {
  const { states, loading } = useLearning();
  if (loading) return <LoadingState label="Loading progress" />;
  const average = states.length ? states.reduce((sum, state) => sum + state.mastery_probability, 0) / states.length : 0;
  const recent = [...states].filter((state) => state.last_practised_at).sort((a, b) => String(b.last_practised_at).localeCompare(String(a.last_practised_at))).slice(0, 3);
  const needsAttention = [...states].sort((a, b) => a.retained_mastery - b.retained_mastery).slice(0, 3);
  const misconceptions = states.filter((state) => state.suspected_misconception);
  return <div className="page-stack"><header className="page-heading"><p className="eyebrow">Learning progress</p><h1>See how your fraction skills are growing</h1><p>Mastery updates from your answers while retained mastery reflects time since practice.</p></header><Card className="overall-card"><div><span>Overall mastery</span><strong>{percent(average)}</strong></div><ProgressBar value={average} label="Overall mastery" /><p>{states.filter((state) => state.mastery_probability >= 0.8).length} of {states.length} concepts mastered</p></Card><section><div className="section-heading"><div><p className="eyebrow">All skills</p><h2>Concept progress</h2></div></div><div className="progress-list">{states.map((state) => <Card key={state.concept_id} className="progress-row"><div className="progress-name"><h3>{humanize(state.concept_id)}</h3><Badge tone={state.mastery_probability >= .8 ? "emerald" : state.mastery_probability >= .6 ? "cyan" : "amber"}>{state.mastery_probability >= .8 ? "Mastered" : state.mastery_probability >= .6 ? "Developing" : "Needs practice"}</Badge></div><div className="progress-value"><ProgressBar value={state.mastery_probability} label={`${humanize(state.concept_id)} mastery`} /><strong>{percent(state.mastery_probability)}</strong></div><small>{state.attempts} attempts · retained {percent(state.retained_mastery)}</small></Card>)}</div></section><div className="two-column"><Card><p className="eyebrow">Recent practice</p><h2>Latest learning evidence</h2>{recent.length ? <ul className="clean-list">{recent.map((state) => <li key={state.concept_id}><span>{humanize(state.concept_id)}</span><strong>{percent(state.mastery_probability)}</strong></li>)}</ul> : <p className="muted">Complete a quick check to build recent evidence.</p>}</Card><Card><p className="eyebrow">Next focus</p><h2>Needs attention</h2><ul className="clean-list">{needsAttention.map((state) => <li key={state.concept_id}><span>{humanize(state.concept_id)}</span><strong>{percent(state.retained_mastery)}</strong></li>)}</ul></Card></div><Card><p className="eyebrow">Learning patterns</p><h2>Ideas RAPID-Learn is watching</h2>{misconceptions.length ? <div className="pattern-list">{misconceptions.map((state) => <div key={state.concept_id}><Badge tone="amber">Reviewing</Badge><span>{humanizeMisconception(state.suspected_misconception ?? "")}</span><small>in {humanize(state.concept_id)}</small></div>)}</div> : <p className="muted">No repeated misconception pattern has enough evidence yet.</p>}</Card></div>;
}
